name: Go Cross-Build & Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        include:
          - goos: linux
            ext: ""
            archive: tar.gz
          - goos: windows
            ext: ".exe"
            archive: zip
          - goos: darwin
            ext: ""
            archive: zip

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binaries
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          go build -o ../dist/dakwak${{ matrix.ext }} main.go

      - name: Archive binaries
        id: archive
        run: |
          cd dist
          ARCHIVE_NAME="dakwak-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.archive }}"
          if [ "${{ matrix.archive }}" == "zip" ]; then
            zip "$ARCHIVE_NAME" dakwak-cli${{ matrix.ext }}
          else
            tar -czf "$ARCHIVE_NAME" dakwak-cli${{ matrix.ext }}
          fi
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_OUTPUT

      - name: Generate SHA256 checksums
        run: |
          cd dist
          sha256sum * > sha256sums.txt

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/${{ steps.archive.outputs.archive_name }}
            dist/sha256sums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

